server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    name: web-system #服务名
  # 服务器文件上传、请求大小设置
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  # 国际化配置
  messages:
    basename: i18n/messages

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mumu?useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: xiaolong


sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  is-read-body: false
  is-read-cookie: true
  is-read-head: true
  is-print: false

#MyBatis-plus
mybatis-plus:
  global-config:
    banner: false
  configuration:
    #不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: null


logging:
  file:
    path: ./logs/mumu/web/${spring.application.name}
  level:
    com.mumu.db.system.mapper: debug # 打印SQL语句

#knife4j配置
#knife4j:
#  basic:
#    enable: true